# Introdução à Inteligência Artificial e Fundamentos de Python

## Introdução ao Pandas DataFrame

O Pandas é uma biblioteca Python para trabalhar com dados organizados em tabelas. Considere, por exemplo, a seguinte tabela:

| Nome  | Idade | Curso      | Nota |
| ----- | ----: | ---------- | ---: |
| Ana   |    20 | Engenharia |  8.5 |
| João  |    22 | Computação |  7.0 |
| Maria |    21 | Engenharia |  9.0 |
| Pedro |    23 | Computação |  6.5 |

Este tabela pode ser representada por um DataFrame, ou uma estrutura de dados tabelado no Python.

In [1]:
import pandas as pd

#### Criação de um DataFrame a partir de um dicionário

In [2]:
import pandas as pd

dados = {
    'Nome': ['Ana', 'João', 'Maria', 'Pedro'],
    'Idade': [20, 22, 21, 23],
    'Curso': ['Engenharia Elétrica', 'Computação',
              'Engenharia de Telecomunicações', 'Computação'],
    'Nota': [8.5, 7.0, 9.0, 6.5]
}
print(dados)

{'Nome': ['Ana', 'João', 'Maria', 'Pedro'], 'Idade': [20, 22, 21, 23], 'Curso': ['Engenharia Elétrica', 'Computação', 'Engenharia de Telecomunicações', 'Computação'], 'Nota': [8.5, 7.0, 9.0, 6.5]}

O DataFrame é construído a partir do dicionário

In [3]:
df=pd.DataFrame(dados)
print(df)
## Importante: os índices 0-3 identificando as linhas são criados automaticamente pelos Pandas

    Nome  Idade                           Curso  Nota
0    Ana     20             Engenharia Elétrica   8.5
1   João     22                      Computação   7.0
2  Maria     21  Engenharia de Telecomunicações   9.0
3  Pedro     23                      Computação   6.5

Acessando uma coluna

In [4]:
df['Nome']

0      Ana
1     João
2    Maria
3    Pedro
Name: Nome, dtype: object

In [5]:
notas=df['Nota']
print(notas)

0    8.5
1    7.0
2    9.0
3    6.5
Name: Nota, dtype: float64

Seleção de várias colunas

In [6]:
df[['Nome', 'Idade', 'Nota']] # atenção ao duplo colchete quando várias colunas são selecionadas!

    Nome  Idade  Nota
0    Ana     20   8.5
1   João     22   7.0
2  Maria     21   9.0
3  Pedro     23   6.5

Seleção de linhas

In [7]:
df.loc[0]

Nome                     Ana
Idade                     20
Curso    Engenharia Elétrica
Nota                     8.5
Name: 0, dtype: object

Seleção de várias linhas

In [8]:
df.loc[0:2]

    Nome  Idade                           Curso  Nota
0    Ana     20             Engenharia Elétrica   8.5
1   João     22                      Computação   7.0
2  Maria     21  Engenharia de Telecomunicações   9.0

In [9]:
df.iloc[0:2]

   Nome  Idade                Curso  Nota
0   Ana     20  Engenharia Elétrica   8.5
1  João     22           Computação   7.0

### Importante:

| Sintaxe                 | Índices retornados |
| ----------------------- | ------------------ |
| `a[0:2]` — NumPy        | 0, 1               |
| `df.iloc[0:2]` — Pandas | 0, 1               |
| `df.loc[0:2]` — Pandas  | **0, 1, 2**        |

Filtragem de dados

Exemplo: Recuperação dos alunos com nota > 7:

In [10]:
df[df['Nota'] > 7]

    Nome  Idade                           Curso  Nota
0    Ana     20             Engenharia Elétrica   8.5
2  Maria     21  Engenharia de Telecomunicações   9.0

Note que o resultado da expressão no par de colchetes interno resulta em:
True
False
True
False

Informações básicas sobre o DataFrame

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nome    4 non-null      object
 1   Idade   4 non-null      int64
 2   Curso   4 non-null      object
 3   Nota    4 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 260.0+ bytes

In [12]:
df.shape

(4, 4)

In [13]:
df.columns

Index(['Nome', 'Idade', 'Curso', 'Nota'], dtype='object')

Estatísticas básicas

In [14]:
df['Nota'].mean()

7.75

In [15]:
df['Nota'].max()

9.0

In [16]:
df['Nota'].min()

6.5

In [17]:
df['Nota'].std()

1.1902380714238083

In [18]:
df['Nota'].describe()

count    4.000000
mean     7.750000
std      1.190238
min      6.500000
25%      6.875000
50%      7.750000
75%      8.625000
max      9.000000
Name: Nota, dtype: float64

Criando uma nova coluna. Como exemplo, uma categoria para alunos aprovados.

In [19]:
df['Aprovado'] = df['Nota'] >= 7
df

    Nome  Idade                           Curso  Nota  Aprovado
0    Ana     20             Engenharia Elétrica   8.5      True
1   João     22                      Computação   7.0      True
2  Maria     21  Engenharia de Telecomunicações   9.0      True
3  Pedro     23                      Computação   6.5     False

#### Criação de um DataFRame a partir de um *array* 2D

In [20]:
import numpy as np

data = np.array([[1, 4], [2, 5], [3, 6]])

df=pd.DataFrame(data)
df

   0  1
0  1  4
1  2  5
2  3  6

Formatação do DataFrame

In [21]:
df = pd.DataFrame(data, index=['Linha1', 'Linha2', 'Linha3'],columns=['Col1', 'Col2'])
df

        Col1  Col2
Linha1     1     4
Linha2     2     5
Linha3     3     6

#### Leitura de um arquivo CSV (*comma-separated values*)

In [22]:
df = pd.read_csv('Files/nba.csv')

In [23]:
df.head() # a instrução head() mostra as primeiras linhas.

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [24]:
df.head(10)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0

In [25]:
df.tail() # mostra as última linhas

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**Exercício:**  Escreva um dicionário Python com os alunos Ana, Bruno, Carlos, Daniela e Eduardo, com idades 20,21,19,22 e 20, respectivamente. Suas notas são 8.5, 6.0, 7.5, 9.0 e 5.5. 
* Transforme o dicionário em um DataFrame
* Mostre apenas a coluna Nota
* Calcule a média das notas
* Mostre os alunos com média maior ou igual a 7
* Crie uma coluna aprovado
* Mostre as primeiras linhas
* E use `describe()`para ver uma análise estatística do DataFrame.