# Introdução à Inteligência Artificial e Fundamentos de Python

## Introdução ao Pandas DataFrame

O Pandas é uma biblioteca Python para trabalhar com dados organizados em tabelas. Considere, por exemplo, a seguinte tabela:

| Nome  | Idade | Curso      | Nota |
| ----- | ----: | ---------- | ---: |
| Ana   |    20 | Engenharia |  8.5 |
| João  |    22 | Computação |  7.0 |
| Maria |    21 | Engenharia |  9.0 |
| Pedro |    23 | Computação |  6.5 |

Este tabela pode ser representada por um DataFrame, ou uma estrutura de dados tabelado no Python.

In [1]:
import pandas as pd

A tabela acima é escrita como um dicionário.

In [2]:
import pandas as pd

dados = {
    'Nome': ['Ana', 'João', 'Maria', 'Pedro'],
    'Idade': [20, 22, 21, 23],
    'Curso': ['Engenharia Elétrica', 'Computação',
              'Engenharia de Telecomunicações', 'Computação'],
    'Nota': [8.5, 7.0, 9.0, 6.5]
}
print(dados)

{'Nome': ['Ana', 'João', 'Maria', 'Pedro'], 'Idade': [20, 22, 21, 23], 'Curso': ['Engenharia Elétrica', 'Computação', 'Engenharia de Telecomunicações', 'Computação'], 'Nota': [8.5, 7.0, 9.0, 6.5]}

O DataFrame é construído a partir do dicionário

In [5]:
df=pd.DataFrame(dados)
print(df)
## Importante: os índices 0-3 identificando as linhas são criados automaticamente pelos Pandas

    Nome  Idade                           Curso  Nota
0    Ana     20             Engenharia Elétrica   8.5
1   João     22                      Computação   7.0
2  Maria     21  Engenharia de Telecomunicações   9.0
3  Pedro     23                      Computação   6.5

Acessando uma coluna

In [6]:
df['Nome']

0      Ana
1     João
2    Maria
3    Pedro
Name: Nome, dtype: object

In [7]:
notas=df['Nota']
print(notas)

0    8.5
1    7.0
2    9.0
3    6.5
Name: Nota, dtype: float64

Seleção de várias colunas

In [9]:
df[['Nome', 'Idade', 'Nota']] # atenção ao duplo colchete quando várias colunas são selecionadas!

    Nome  Idade  Nota
0    Ana     20   8.5
1   João     22   7.0
2  Maria     21   9.0
3  Pedro     23   6.5

Seleção de linhas

In [10]:
df.loc[0]

Nome                     Ana
Idade                     20
Curso    Engenharia Elétrica
Nota                     8.5
Name: 0, dtype: object

Seleção de várias linhas

In [11]:
df.loc[0:2]

    Nome  Idade                           Curso  Nota
0    Ana     20             Engenharia Elétrica   8.5
1   João     22                      Computação   7.0
2  Maria     21  Engenharia de Telecomunicações   9.0

In [12]:
df.iloc[0:2]

   Nome  Idade                Curso  Nota
0   Ana     20  Engenharia Elétrica   8.5
1  João     22           Computação   7.0

### Importante:

| Sintaxe                 | Índices retornados |
| ----------------------- | ------------------ |
| `a[0:2]` — NumPy        | 0, 1               |
| `df.iloc[0:2]` — Pandas | 0, 1               |
| `df.loc[0:2]` — Pandas  | **0, 1, 2**        |

Filtragem de dados

Exemplo: Recuperação dos alunos com nota > 7:

In [14]:
df[df['Nota'] > 7]

    Nome  Idade                           Curso  Nota
0    Ana     20             Engenharia Elétrica   8.5
2  Maria     21  Engenharia de Telecomunicações   9.0

Note que o resultado da expressão no par de colchetes interno resulta em:
True
False
True
False

Informações básicas sobre o DataFrame

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nome    4 non-null      object
 1   Idade   4 non-null      int64
 2   Curso   4 non-null      object
 3   Nota    4 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 260.0+ bytes

In [16]:
df.shape

(4, 4)

In [17]:
df.columns

Index(['Nome', 'Idade', 'Curso', 'Nota'], dtype='object')

Estatísticas básicas

In [18]:
df['Nota'].mean()

7.75

In [19]:
df['Nota'].max()

9.0

In [20]:
df['Nota'].min()

6.5

In [21]:
df['Nota'].std()

1.1902380714238083

In [22]:
df['Nota'].describe()

count    4.000000
mean     7.750000
std      1.190238
min      6.500000
25%      6.875000
50%      7.750000
75%      8.625000
max      9.000000
Name: Nota, dtype: float64

Criando uma nova coluna. Como exemplo, uma categoria para alunos aprovados.

In [24]:
df['Aprovado'] = df['Nota'] >= 7
df

    Nome  Idade                           Curso  Nota  Aprovado
0    Ana     20             Engenharia Elétrica   8.5      True
1   João     22                      Computação   7.0      True
2  Maria     21  Engenharia de Telecomunicações   9.0      True
3  Pedro     23                      Computação   6.5     False

Leitura de um arquivo CSV (*comma-separated values*)

In [30]:
df = pd.read_csv('Files/titanic.csv')

In [32]:
df.head() # a instrução head() mostra as primeiras linhas.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [33]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [34]:
df.tail() # mostra as última linhas

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

**Exercício:**  Escreva um dicionário Python com os alunos Ana, Bruno, Carlos, Daniela e Eduardo, com idades 20,21,19,22 e 20, respectivamente. Suas notas são 8.5, 6.0, 7.5, 9.0 e 5.5. 
* Transforme o dicionário em um DataFrame
* Mostre apenas a coluna Nota
* Calcule a média das notas
* Mostre os alunos com média maior ou igual a 7
* Crie uma coluna aprovado
* Mostre as primeiras linhas
* E use `describe()`para ver uma análise estatística do DataFrame.